sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install pybuilder coveralls pep257 flake8
  - pyb -v install_dependencies

script:
  - pyb -v -X verify analyze
after_success:
  - flake8 --max-line-length=99 src/main/
  - pep257 src/main/
  - coveralls
